### ISSUE TITLE
engine stops automatically after starting, then cannot be started again for that plane

### ISSUE THREAD

**Issue by MisterE123** [APercy/pa28#2]
you can turn on the engine exactly once per plane, and its impossible to take off, as the engine turns off after a few seconds

Hmm... the issue of the motor stopping occurs for all the planes, regardless of if air_utils is installed. So its something else...

Feel free to close

**Comment by APercy** [comment]
Put fuel first, the airplane comes with the minimal fuel to not damage the carburetor :)
Punch it against the plane. See the level at fuel gauge (marked with a green F)
And do not forget, only takeoff with sufficient fuel for your destination and alternative ;)

**Comment by MisterE123** [comment]
oh thats it lol, ok. maybe, it would help, if when you have the hud enabled, and the fuel is low, a 'Low fuel!' message flashes in the corner of the screen
